# Generated by Django 3.1.1 on 2020-10-02 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30, null=True, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('street_addr', models.CharField(max_length=50, null=True, verbose_name='Street Address')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=2, null=True, verbose_name='State')),
                ('zip_code', models.CharField(max_length=30, null=True, verbose_name='Zip Code')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='Phone Number')),
                ('years_participated', models.IntegerField(null=True, verbose_name='Years in WF Baseball')),
                ('unsubscribe', models.BooleanField(default=False, help_text='Check if you would not like to receive any communications from West Fargo Baseball', verbose_name='Unsubscribe to all Communications')),
                ('project_updates', models.BooleanField(default=True, help_text='Check if you would like to get updates about West Fargo Baseball projects', verbose_name='Subscribe to Project Updates')),
                ('news_events', models.BooleanField(default=True, help_text='Check if you would like to get general news about West Fargo Baseball', verbose_name='Subscribe to West Fargo Baseball News')),
                ('comm_pref', models.CharField(choices=[('E', 'Email'), ('M', 'Mail'), ('P', 'Phone'), ('T', 'Text Messages')], default='email', help_text='Choose the method you would prefer West Fargo Baseball use to contact you. Note: West Fargo Baseball may use email as primary for some communications', max_length=1, verbose_name='Communications Preference')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_emailed', models.DateTimeField(null=True)),
                ('web_updated', models.BooleanField(default=False)),
            ],
        ),
    ]
