# Generated by Django 3.1.1 on 2020-10-12 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contactforms_app', '0002_auto_20201004_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='comm_pref',
            field=models.CharField(choices=[('E', 'Email'), ('M', 'Mail'), ('P', 'Phone'), ('T', 'Text Messages')], default='email', max_length=1, verbose_name='Communications Preference'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='news_events',
            field=models.BooleanField(default=True, verbose_name='Subscribe to West Fargo Baseball News'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='project_updates',
            field=models.BooleanField(default=True, verbose_name='Subscribe to Project Updates'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='unsubscribe',
            field=models.BooleanField(default=False, verbose_name='Unsubscribe to all Communications'),
        ),
    ]
