# Generated by Django 3.1.2 on 2020-10-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactforms_app', '0003_auto_20201012_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='comm_pref',
            field=models.CharField(choices=[('E', 'Email'), ('M', 'Mail'), ('P', 'Phone'), ('T', 'Text Messages')], default='email', help_text='Choose the method you would prefer West Fargo Baseball use to contact you. Note: West Fargo Baseball may use email as primary for some communications', max_length=1, verbose_name='Communications Preference'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='news_events',
            field=models.BooleanField(default=True, help_text='Check if you would like to get general news about West Fargo Baseball', verbose_name='Subscribe to West Fargo Baseball News'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='project_updates',
            field=models.BooleanField(default=True, help_text='Check if you would like to get updates about West Fargo Baseball projects', verbose_name='Subscribe to Project Updates'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='unsubscribe',
            field=models.BooleanField(default=False, help_text='Check if you would not like to receive any communications from West Fargo Baseball', verbose_name='Unsubscribe to all Communications'),
        ),
    ]
