# Generated by Django 3.1.2 on 2020-10-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactforms_app', '0004_auto_20201012_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='unsubscribe',
            field=models.BooleanField(default=False, help_text='Check if you wish to unsubscribe from all communications from West Fargo Baseball', verbose_name='Unsubscribe to all Communications'),
        ),
    ]
