# Generated by Django 3.1.2 on 2020-10-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactforms_app', '0005_auto_20201012_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='fname',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='First Name'),
            preserve_default=False,
        ),
    ]
