# Generated by Django 3.1.2 on 2020-10-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactforms_app', '0007_auto_20201013_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='duplicate',
        ),
    ]
