# Generated by Django 3.1.2 on 2020-10-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactforms_app', '0008_remove_contacts_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
