# Generated by Django 3.1.2 on 2020-10-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactforms_app', '0010_auto_20201013_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='years_participated',
            field=models.IntegerField(null=True, verbose_name='Years in WF Baseball'),
        ),
    ]
