# Generated by Django 3.0.10 on 2020-11-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactforms_app', '0013_auto_20201024_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='comm_pref',
            field=models.CharField(blank=True, choices=[('E', 'Email'), ('M', 'Mail'), ('P', 'Phone'), ('T', 'Text Messages')], default='email', help_text='Choose the method you would prefer the Moorhead Brewers use to contact you. Note: The Moorhead Brewers may use email as primary for some communications', max_length=1, verbose_name='Communications Preference'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='news_events',
            field=models.BooleanField(blank=True, default=True, help_text='Check if you would like to get general news about our the Moorhead Brewers', verbose_name='Subscribe to Moorhead Brewers News'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='project_updates',
            field=models.BooleanField(blank=True, default=True, help_text='Check if you would like to get updates about the Moorhead Brewers projects', verbose_name='Subscribe to Project Updates'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='unsubscribe',
            field=models.BooleanField(blank=True, default=False, help_text='Check if you wish to unsubscribe from all communications from the Moorhead Brewers', verbose_name='Unsubscribe to all Communications'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='years_participated',
            field=models.IntegerField(blank=True, verbose_name='# of Years in Program'),
        ),
    ]
